In [1]:
import math

In [2]:
import torch

In [3]:
from termcolor import colored
print(colored('hello', 'red'), colored('world', 'green'))
print(colored("hello red world", 'red'))

hello world
hello red world


In [43]:
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        w = 0.5
        self.w = torch.nn.Parameter(torch.full((1,), w, dtype = torch.float32))
                                             
        pass#def 
    
    def forward(self, x):
        x = self.w*x
        return x
        pass#def 
    pass#class
model = Model()
loss_fn = torch.nn.L1Loss()
opt = torch.optim.RMSprop(model.parameters(), lr = 1e-4)

X = torch.tensor([0.1], dtype = torch.float32)
Y = torch.tensor([0.1], dtype = torch.float32)

for epoch in range(10):
    opt.zero_grad()
    pred = model(X)
    loss = loss_fn(pred, Y)
    loss.backward()
    opt.step()
    
    print(model.w.data)
    pass



tensor([0.5010])
tensor([0.5017])
tensor([0.5023])
tensor([0.5028])
tensor([0.5032])
tensor([0.5037])
tensor([0.5040])
tensor([0.5044])
tensor([0.5047])
tensor([0.5051])


In [31]:
class Model(torch.nn.Module):
    def __init__(self, order):
        super().__init__()
        w = 0.5
        self.order = order
        w_like = math.pow(w, 1/self.order)
        self.w_like = torch.nn.Parameter(torch.full((1,), w_like, dtype = torch.float32))
                                             
        pass#def 
    
    def forward(self, x):
        x = self.get_w()*x
        return x
        pass#def 
    def get_w(self):
        return torch.pow(self.w_like, self.order)
    pass#class
models = [Model(order) for order in [1,2,3,5,10,20]]
loss_fn = torch.nn.MSELoss()


X = torch.tensor([0.1], dtype = torch.float32)
Y = torch.tensor([0.1], dtype = torch.float32)

for model in models:
    print(colored(F"{model.order}---------------","green"))
    opt = torch.optim.RMSprop(model.parameters(), lr = 1e-3)
    
    for epoch in range(1000):
        opt.zero_grad()
        pred = model(X)
        loss = loss_fn(pred, Y)
        if loss.item()<1e-8:
            print(epoch)
            break
            pass
        loss.backward()
        opt.step()
        #print(model.w_like)
        pass    
    w = model.get_w()
    print(w.data)
    pass

1---------------
722
tensor([0.9990])
2---------------
406
tensor([0.9990])
3---------------
265
tensor([0.9990])
5---------------
138
tensor([0.9990])
10---------------
47
tensor([0.9990])
20---------------
14
tensor([0.9991])


In [52]:
class Model(torch.nn.Module):
    def __init__(self, order):
        super().__init__()
        w = 1
        b = 0.1
        self.order = order
        w_like = math.pow(w, 1/self.order)
        b_like = math.pow(b, 1/self.order)
        self.w_like = torch.nn.Parameter(torch.full((1,), w_like, dtype = torch.float32))
        self.b_like = torch.nn.Parameter(torch.full((1,), b_like, dtype = torch.float32))
                                             
        pass#def 
    
    def forward(self, x):
        x = self.get_w()*x + self.get_b()
        return x
        pass#def 
    def get_w(self):
        return torch.pow(self.w_like, self.order)
        pass#def 
    def get_b(self):
        return torch.pow(self.b_like, self.order)
        pass#def
    pass#class
models = [Model(order) for order in [1,-0.5,2,2.263, -1,3,4,4.34, -3, 5,10,15, 20, 0.5, 0.1,   ]]
loss_fn = torch.nn.MSELoss()


X = torch.tensor([1], dtype = torch.float32)
Y = torch.tensor([3], dtype = torch.float32)

for model in models:
    print(colored(F"{model.order}---------------","green"))
    opt = torch.optim.RMSprop(model.parameters(), lr = 1e-3)
    
    for epoch in range(2000):
        opt.zero_grad()
        pred = model(X)
        loss = loss_fn(pred, Y)
        if loss.item()<1e-8:
            print(epoch)
            break
            pass
        loss.backward()
        opt.step()
        #print(model.w_like)
        pass    
    w = model.get_w()
    print(w.data)
    b = model.get_b()
    print(b.data)
    pass

1---------------
1342
tensor([1.9500])
tensor([1.0500])
-0.5---------------
767
tensor([2.8996])
tensor([0.1003])
2---------------
756
tensor([2.2579])
tensor([0.7420])
2.263---------------
677
tensor([2.3076])
tensor([0.6923])
-1---------------
677
tensor([2.8944])
tensor([0.1055])
3---------------
517
tensor([2.4089])
tensor([0.5910])
4---------------
381
tensor([2.4927])
tensor([0.5072])
4.34---------------
347
tensor([2.5129])
tensor([0.4870])
-3---------------
347
tensor([2.8540])
tensor([0.1459])
5---------------
293
tensor([2.5442])
tensor([0.4557])
10---------------
110
tensor([2.6433])
tensor([0.3566])
15---------------
56
tensor([2.6736])
tensor([0.3263])
20---------------
33
tensor([2.6881])
tensor([0.3118])
0.5---------------
tensor([1.6654])
tensor([1.2741])
0.1---------------
tensor([1.1168])
tensor([0.6413])
